<?php
$works = [
    [
        'class_vignets' => 'planche4 case1',
        'class_job' => 'case2',
        'job' => 'Journaliste indépendant',
        'year' => 1929,
        'location' => 'Belgique',
        'class_border1' => 'planche3 case3',
        'class_border2' => 'planche1 case4',
        'class_talking' => 'case5',
        'talking' => "J'ai acquis une certaine facilité à me mêler d'affaires qui ne me regarde pas...",
        'source_img' => './img/tintin-writing.png',
        'class_img' => 'jumelle',
        'class_border3' => 'planche2 case6',
    ],
    [
        'class_vignets' => 'planche5 case7"',
        'class_job' => 'case8',
        'job' => 'Pilote en tout genre',
        'year' => 2001,
        'location' => 'New-York',
        'class_border1' => 'planche6 case9',
        'class_border2' => 'planche3 case10',
        'class_talking' => 'case11',
        'talking' => "Sous-marin, avion , moto, jeep, chameau, fusée...Même pas peur !",
        'source_img' => '',
        'class_img' => '',
        'class_border3' => 'planche4 case12',
    ],
    [
        'class_vignets' => 'planche2 case13"',
        'class_job' => 'case14',
        'job' => 'Traficant de drogue',
        'year' => 1993,
        'location' => 'Colombie',
        'class_border1' => 'planche1 case15',
        'class_border2' => 'planche5 case16',
        'class_talking' => 'case17',
        'talking' => "J'ai développé mon réseau de contact professionnel jusqu'en Colombie",
        'source_img' => './img/méchants.png',
        'class_img' => 'bad_boys',
        'class_border3' => 'planche6 case18',
    ],
    [
        'class_vignets' => 'planche3 case19"',
        'class_job' => 'case20',
        'job' => 'Roi Maya',
        'year' => 1949,
        'location' => 'Pérou',
        'class_border1' => 'planche2 case21',
        'class_border2' => 'planche1 case22',
        'class_talking' => 'case23',
        'talking' => "J'ai développé ma capacité managériale et mon sens de l'autorité.",
        'source_img' => '',
        'class_img' => '',
        'class_border3' => 'planche4 case24',
    ],
/*     [
        'class_vignets' => '"',
        'class_job' => '',
        'job' => 'Roi Maya',
        'year' => 1949,
        'location' => 'Pérou',
        'class_border1' => '',
        'class_border2' => '',
        'class_talking' => '',
        'talking' => "J'ai développé ma capacité managériale et mon sens de l'autorité.",
        'source_img' => '',
        'class_img' => '',
        'class_border3' => '',
    ], */
];