<?php
$educations = [
    [
        'class_vignets' => 'planche4 case1',
        'class_job' => 'case2',
        'job' => 'Formation auprès du Professeur Tournesol',
        'year' => 1941,
        'location' => 'France',
        'class_border1' => 'planche3 case3',
        'class_border2' => 'planche1 case4',
        'class_talking' => 'case5',
        'talking' => "J'ai participé à des inventions pour le concours Lépine, jusqu'à étudier la physique nucléaire avec cet éminent Professeur.",
        'source_img' => './img/tournesol.png',
        'class_img' => '',
        'class_border3' => 'planche2 case6',
    ],
    [
        'class_vignets' => 'planche5 case7"',
        'class_job' => 'case8',
        'job' => 'Années sabbatiques',
        'year' => 1941,
        'location' => 'Afrique',
        'class_border1' => 'planche6 case9',
        'class_border2' => 'planche3 case10',
        'class_talking' => 'case11',
        'talking' => "J'ai voyagé à travers le monde et appris auprès d'un marin au langage fleurie et l'haleine chargée.",
        'source_img' => './img/Haddock.png',
        'class_img' => '',
        'class_border3' => 'planche4 case12',
    ],
    [
        'class_vignets' => 'planche2 case13"',
        'class_job' => 'case14',
        'job' => 'Stage de découverte d\'entreprises',
        'year' => 1932,
        'location' => 'France',
        'class_border1' => 'planche1 case15',
        'class_border2' => 'planche5 case16',
        'class_talking' => 'case17',
        'talking' => "J'ai eu la chance de découvrir le métier de détective privé auprès de deux experts en confusions, malentendus et méprises !",
        'source_img' => './img/dupont.jpeg',
        'class_img' => '',
        'class_border3' => 'planche6 case18',
    ],
    [
        'class_vignets' => 'planche3 case19"',
        'class_job' => 'case20',
        'job' => 'Ecole de la vie',
        'year' => 1929,
        'location' => 'Belgique',
        'class_border1' => 'planche2 case21',
        'class_border2' => 'planche1 case22',
        'class_talking' => 'case23',
        'talking' => "J'ai beaucoup appris après mon voyage en union-soviétique. J'ai donc voulu m'essayer dans d'autres activités.",
        'source_img' => './img/milou.png',
        'class_img' => '',
        'class_border3' => 'planche4 case24',
    ],
];